# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_mult_JRNMM_ <- function(mat, vec) {
    .Call(`_StrangSplittingJRNMM_mv_mult_JRNMM_`, mat, vec)
}

sigmoid_JRNMM_Cpp_ <- function(x, vmax, v0, r) {
    .Call(`_StrangSplittingJRNMM_sigmoid_JRNMM_Cpp_`, x, vmax, v0, r)
}

exponential_matrix_JRNMM_ <- function(dGamma, h) {
    .Call(`_StrangSplittingJRNMM_exponential_matrix_JRNMM_`, dGamma, h)
}

covariance_matrix_JRNMM_ <- function(dGamma, dSigma, h) {
    .Call(`_StrangSplittingJRNMM_covariance_matrix_JRNMM_`, dGamma, dSigma, h)
}

linear_JRNMM_Cpp_ <- function(vec, dm, xi) {
    .Call(`_StrangSplittingJRNMM_linear_JRNMM_Cpp_`, vec, dm, xi)
}

nonlinear_JRNMM_Cpp_ <- function(N, vec, h, Theta, Rho, K) {
    .Call(`_StrangSplittingJRNMM_nonlinear_JRNMM_Cpp_`, N, vec, h, Theta, Rho, K)
}

JRNMM_Splitting_Cpp_ <- function(N_i, grid_i, h_i, startv, dm_i, meanVec_i, covMat_i, Theta_i, Rho_i, K_i) {
    .Call(`_StrangSplittingJRNMM_JRNMM_Splitting_Cpp_`, N_i, grid_i, h_i, startv, dm_i, meanVec_i, covMat_i, Theta_i, Rho_i, K_i)
}

meanHO_ <- function(N, h, expM, x) {
    .Call(`_StrangSplittingJRNMM_meanHO_`, N, h, expM, x)
}

fastJRNMM_Splitting_Cpp_ <- function(N, grid, h, start, dGamma, dSigma, Theta, Rho, K) {
    .Call(`_StrangSplittingJRNMM_fastJRNMM_Splitting_Cpp_`, N, grid, h, start, dGamma, dSigma, Theta, Rho, K)
}

observedJRNMM_ <- function(N, sol) {
    .Call(`_StrangSplittingJRNMM_observedJRNMM_`, N, sol)
}

